on: [push]
jobs:
  Compile tex:	
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag resume
      - run: sudo docker run --name=resume resume
      - run: mkdir -p result
      - run: sudo docker cp resume:code/cv.pdf ./result/
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: ./result/cv.pdf

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: './result/cv.pdf'
          branch: cv_pdf
          message: 'update cv'
