on: [push]
jobs:
  Compile-tex:	
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          remove: 'cv.pdf'
          branch:  cv_pdf
          message: 'deleted old cv'
      - run: docker build . --file Dockerfile --tag resume
      - run: sudo docker run --name=resume resume 
      - run: sudo docker cp resume:code/cv.pdf ./
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: ./cv.pdf

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: './cv.pdf'
          branch: cv_pdf
          message: 'update cv'
